# --- SonarCloud Connection Details ---
sonar.projectKey=Sovereign-AI-System  
sonar.organization=Aanidhay Aggarwal            

# --- Project Information ---
sonar.projectName=Sovereign AI Suite
sonar.projectVersion=1.0

# --- Source Code Location ---
sonar.sources=.

# --- Exclusions ---
sonar.exclusions=**/venv/**,**/__pycache__/**,**/.terraform/**,**/*.csv,**/*.jpg